export const STATE_SEARCH = "STATE_SEARCH";
export const NAME_SEARCH = "NAME_SEARCH";
export const TOGGLE_TYPE_SEARCH = "TOGGLE_TYPE_SEARCH";
export const NAME_SEARCH_SUBMIT = "NAME_SERACH_SUBMIT";
export const STATE_SEARCH_SUBMIT = "STATE_SERACH_SUBMIT";
export const TYPE_SEARCH_SUBMIT = "TYPE_SERACH_SUBMIT";
